### ISSUE TITLE
Add playbook setup-wifi.yaml

### ISSUE THREAD

**Issue by vareso** [blackthrow/playbooks#4]
The playbook will install and configure wpa_supplicant. It reads variables from `vars/wifi.yaml`:

```
wifi:
  wlan0:
    essid: HomeLan
    passphrase: MyPassword123
    # other options may be defined, this is just the bare minimum
```

These data will be used to generate a file `/etc/wpa_supplicant/wpa_supplicant-<interface>.conf`.

To start the wpa_supplicant using this configuration, use: `systemctl (start|enable) wpa_supplicant@<interface>.service`.

At last a file `/etc/systemd/network/<interface>.network` should be created to enable management by systemd. Reload the service `systemctl reload systemd-networkd`.

Some references:
https://wiki.archlinux.org/index.php/WPA_supplicant#Connecting_with_wpa_passphrase
https://wiki.archlinux.org/index.php/systemd-networkd
